@startuml 
skinparam monochrome true

|#gray|Engineering Change Propasal|
start 
  :Idea / Change Propasal; 
repeat 
repeat

|Change Implementation Plan| 
  :(Re)Define Change Implementation Plan; 
  :Submit / Request Plan; 
  :Access Change Plan;
  note left
    Technical Feasibility 
  end note 
repeat while (Accepted) is (Insufficient)
: Approve Change Plan; 
  note left
    Business Feasibility  
  end note 
repeat while (Approved) is (Denied)
|#gray|Change Request|
: Implement Change; 
if (Verify Change) then (faultless)
    : Accept New Baseline; 
else (flawed)
    : Rollback Implementation; 
endif 
: Close Change Request; 

stop 
@enduml