@startsalt
{+
Description     | "                 "
Requester:      | ^Employee Id^
Department:     | ^Department Id^
Change Level    | ^Major / Minor^
Affect Partied  | ^3rd Party Id^
Component / Solution | ^Component Id^
Inital Baseline | ^Baseline Version Id^
New Baseline | "Version Id       "
Technical Verification | "                 "
Business Verification | "                 "
Implementation Procedure | "                 "
Rollback Procedure | "                 "
Implementer | ^Employee Id^
Accessor | ^Employee Id^
Approver | ^Employee Id^
}
@endsalt