@startuml
skinparam monochrome true
start
:Baggage enters system;

:Baggage conveyed to additional screening;

if (Luggage goes through additional screening) then (Rejected)
    :Conveyed to Ultimate control area;
    :Baggage removed from system;
    :Baggage is transported manually to search area;
    if (Baggage is insecure) then (Yes)
     if (Baggage is too dangerous) then (Yes)
        :Baggage is destroyed;
        stop
    else (No)
        :Baggage is taken aside\n(further action is out of scope);
        stop
    endif
  endif  
  :Baggage reintroduced to system;
  
else (Cleared)
  
endif
  :Baggage continues out of system;
stop


@enduml